---
- name: Creating the cluster resources to manage Apache HTTP Server
  hosts: nodes[0]
  become: yes
  gather_facts: no

  tasks:
  - name: Collecting the existing resources
    command:
      cmd: pcs resource config
    changed_when: false
    register: resources

  - name: Ensuring the firstwebfs resource exists
    command:
      cmd: #FIXME#
    when: "' firstwebfs ' not in resources['stdout']"

  - name: Ensuring the firstwebserver resource exists
    command:
      cmd: #FIXME#
    when: "' firstwebserver ' not in resources['stdout']"

  - name: Ensuring the firstwebip resource exists
    command:
      cmd: #FIXME#
    when: "' firstwebip ' not in resources['stdout']"
...
